[ADD]open_academy: Added new models Courses and Sessions with menu vi…
UlisesRivadeneyra/Open-Academy pull request #3
Opened 2022-09-30 16:30 UTC by UlisesRivadeneyra

…ew T#60931

2022-09-30 22:14 UTC, edy1192 requested changes

2022-09-30 22:14 UTC, edy1192 commented on open_academy/models/course.py
> +    responsible_user = fields.Many2one(comodel_name="res.users", ondelete="set null")
You don't need to add comodel_name

```suggestion
    responsible_user = fields.Many2one("res.users", ondelete="set null")
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/models/course.py
> +    _name = "openacademy.sessions"
Use name in singular form please https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models

```suggestion
    _name = "openacademy.session"
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/models/course.py
> +    _description = "Sessions"
```suggestion
    _description = "Session"
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/models/course.py
> +    name = fields.Char(string="Sessions", required=True)
```suggestion
    name = fields.Char(string="Session", required=True)
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/models/course.py
> +    course_id = fields.Many2one(comodel_name='openacademy.course', ondelete='')
```suggestion
    instructor = fields.Many2one('res.partner', ondelete="set null")
    course_id = fields.Many2one('openacademy.course', ondelete='')
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_menu_views.xml
> +    <menuitem id="open_academy_session_menu" name="Open Academy Sessions" action="session_list_action"/>
You need a root menu before others menus.

```suggestion
    <menuitem id="open_academy_root_menu" name="Open Academy" sequence="1" />
    <menuitem id="open_academy_course_menu" name="Courses" sequence="1" parent="open_academy_root_menu" action="openacademy_course_action_list"/>
    <menuitem id="open_academy_session_menu" name="Sessions" sequence="2" parent="open_academy_root_menu" action="session_list_action"/>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please move all session's views to another file `open_academy_session_views.xml`

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +        <field name="name">List all courses</field>
```suggestion
        <field name="name">open.academy.course.action.list</field>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +        <field name="name">Sessions</field>
This is the name of the action
```suggestion
        <field name="name">session.list.action</field>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +        <field name="res_model">openacademy.sessions</field>
```suggestion
        <field name="res_model">openacademy.session</field>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +            <search string="">
Remove string attribute please
```suggestion
            <search>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +    <record id="openacademy_sessions_form" model="ir.ui.view">
```suggestion
    <record id="openacademy_session_form" model="ir.ui.view">
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +        <field name="name">openacademy.sessions.form</field>
```suggestion
        <field name="name">openacademy.session.form</field>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +        <field name="model">openacademy.sessions</field>
```suggestion
        <field name="model">openacademy.session</field>
```

2022-09-30 22:14 UTC, edy1192 commented on open_academy/views/course_views.xml
> +    <!-- This is the tree view of course-->
```suggestion
    <!-- This is the tree view of session-->
```

And where is the session's tree view?

2022-09-30 22:14 UTC, edy1192 commented on open_academy/README.rst
> +**This file is going to be generated by oca-gen-addon-readme.**
Please remove all this and add a description for this module.

2022-09-30 22:15 UTC, edy1192 commented
@UlisesRivadeneyra please add a description for your PR

2022-10-03 17:01 UTC, UlisesRivadeneyra commented on open_academy/views/course_views.xml
> +<?xml version="1.0" encoding="utf-8"?>
HERE

2022-10-04 15:48 UTC, UlisesRivadeneyra commented
Hey @edy1192 Im ready to check my second PR, thanks for your time, greetings!!!

2022-10-04 16:43 UTC, edy1192 requested changes

2022-10-04 16:43 UTC, edy1192 commented on .flake8
> +[flake8]
Please remove this file and add it to gitignore file.

2022-10-04 16:43 UTC, edy1192 commented on open_academy/demo/open_academy_demo.xml
> +
Remove blank lines please

2022-10-04 16:43 UTC, edy1192 commented on open_academy/__manifest__.py
> +        'views/open_academy_session_views.xml'
This goes after views.
```suggestion
        'views/open_academy_session_views.xml',
        'views/open_academy_menu_views.xml'
```

2022-10-04 16:43 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +
Remove blank lines please.

2022-10-04 16:43 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +    title = fields.Char(string="Courses", required=True)
```suggestion
    title = fields.Char(string="Course", required=True)
```

2022-10-04 16:43 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    name = fields.Char(string="Sessions", required=True)
```suggestion
    name = fields.Char(string="Session", required=True)
```

2022-10-04 16:43 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    instructor = fields.Many2one('res.partner', ondelete="set null")
See the guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#38fields
```suggestion
    instructor_id = fields.Many2one('res.partner', ondelete="set null")
```

2022-10-04 16:43 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> +        <field name="name">open.academy.course.action.list</field>
Sorry, I got confused with this. I thought it was the view and it is the action. This is what the user sees when he opens the view, so please change the name.

```suggestion
        <field name="name">Courses</field>
```
Sorry 🙊

2022-10-04 16:43 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> +    </record>
Move this to `open_academy_session_views.xml` file please.

And sorry, I got confused with this. I thought it was the view and it is the action. This is what the user sees when he opens the view, so please change the name.

```suggestion
        <field name="name">Sessions</field>
```
Sorry 🙊

2022-10-04 16:43 UTC, edy1192 commented on open_academy/views/open_academy_session_views.xml
> +                    </group>
Where are `course_id` and `instructor_id` fields?

2022-10-04 19:28 UTC, UlisesRivadeneyra commented
@edy1192 Hi, i already change the comments that you did, my PR is ready for the new review, thanks!! Greetings, Ulises!!

2022-10-04 22:38 UTC, edy1192 approved these changes

2022-10-04 22:38 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +    responsible_user = fields.Many2one("res.users", ondelete="set null")
In anothe PR please change this field. Follow the naming guidelines for Many2One fields

```suggestion
    responsible_user_id = fields.Many2one("res.users", ondelete="set null")
```

2022-10-04 22:38 UTC, merged

2022-10-04 22:39 UTC, edy1192 commented
Merged @UlisesRivadeneyra 👏🏼