[ADD]open_academy: Added partner module with his view T#60931
UlisesRivadeneyra/Open-Academy pull request #4
Opened 2022-10-06 20:44 UTC by UlisesRivadeneyra

-Added open_academy_partner_views.xml
-Added sql constraints in open_cademy_course
-Rewrite of the copy function in open_academy_course
-Added new fields in open_academy_session
-Added new api decorators in open_academy_session(constraints and compute)
-Added new calendar view in open_academy_session_views
-Added color variation on fields of tree in open_academy<-session_views
-Added partner category in open_academy_partner_views

Im currently in the [Search views excersice ](https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#id4)

2022-10-06 21:25 UTC, UlisesRivadeneyra commented
@edy1192 Hi!!
This is my new PR i added the description above, its ready to be reviewed
Greeting, Ulises!!

2022-10-07 17:56 UTC, edy1192 requested changes

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +            "The title of the course should not be the description"
```suggestion
            "The title of the course should not be the same that description."
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +        ('name_unique', 'UNIQUE(title)', "The course title must be unique"),
```suggestion
        ('name_unique', 'UNIQUE(title)', "The course title must be unique."),
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_partner.py
> +class Partner(models.Model):
```suggestion
class ResPartner(models.Model):
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _get_end_date(self):
```suggestion
    def _compute_end_date(self):
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        compute='_compute_get_end_date',
```suggestion
        compute='_compute_end_date',
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        inverse='_inverse_set_end_date'
```suggestion
        inverse='_inverse_end_date'
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _taken_seats(self):
```suggestion
    def _taken_seats(self):_compute_taken_seats
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                record.taken_seats = 100.0 * len(record.attendee_ids) / record.seats
```suggestion
                record.taken_seats = 100.0 * (len(record.attendee_ids) / record.seats)
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _verify_valid_seats(self):
Change this name, see the guidelines for onchange methods https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'title': "Incorrect 'seats' value",
```suggestion
                    'title': "Incorrect 'seats' value.",
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'message': "The number of available seats may not be negative",
```suggestion
                    'message': "The number of available seats may not be negative.",
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'title': "Too many attendees",
```suggestion
                    'title': "Too many attendees.",
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'message': "Increase seats or remove excess attendees",
```suggestion
                    'message': "Increase seats or remove excess attendees.",
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                raise exceptions.ValidationError_("A session's instructor can't be an attendee")
Why `_()`? That method is for Internationalization chapter.

2022-10-07 17:56 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        for record in self:
```suggestion
        for record in self.filtered('instructor_id'):
```

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> -                    </notebook>
Why do you remove the description field?

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_menu_views.xml
> +    parent="open_academy_root_menu" action="openacademy_partner_action_list"/>
Remove this menu. This is not necessary, Odoo has an app for contacts. Find it in apps and install it.

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_partner_views.xml
> +    </record>
Remove all this. This is not necessary, Odoo has an app for contacts. Find it in apps and install it.

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_partner_views.xml
> +    </record>
Remove all this. This is not necessary, Odoo has an app for contacts. Find it in apps and install it.

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_partner_views.xml
> +    </record>
This is no correct. You need to inherit the `base.view_partner_form` and use xpath.

2022-10-07 17:56 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
Where is the search views exercise? 

```
 Exercise

Search views

Add a button to filter the courses for which the current user is the responsible in the course search view. Make it selected by default.

Add a button to group courses by responsible user.
```

2022-10-10 16:50 UTC, UlisesRivadeneyra commented
Hi @edy1192 i already added the change in the code, hope that you can give it a check
Greetings, Ulises!!

2022-10-10 21:23 UTC, edy1192 requested changes

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/res_partner.py
> +    )
What is this? 

This exercise is completed with the functional explanation that I gave you about the categories.

Exercise says:

```
More complex domains

Create new partner categories Teacher / Level 1 and Teacher / Level 2. The instructor for a session can be either an instructor or a teacher (of any level).
```

2022-10-10 21:23 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> +                        <field name="session_ids"></field>
Move this field to a notebook section please.

2022-10-10 21:23 UTC, edy1192 commented on open_academy/views/open_academy_session_views.xml
> +        <field name="name">openacademy.session_view_tree</field>
```suggestion
        <field name="name">openacademy.session.tree.view</field>
```

2022-10-10 21:23 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> +                <field name ="description"/>
```suggestion
                <field name="description"/>
```

2022-10-10 21:23 UTC, edy1192 commented on open_academy/views/res_partner_views.xml
> +                            <field name="instructor_category" />
This field is not necessary.

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        compute='_compute_get_end_date',
```suggestion
        compute='_compute_end_date',
```

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        inverse='_inverse_set_end_date'
```suggestion
        inverse='_inverse_end_date'
```

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _get_end_date(self):
Pending https://github.com/UlisesRivadeneyra/Open-Academy/pull/4/files#r990351418

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _taken_seats(self):
Pending https://github.com/UlisesRivadeneyra/Open-Academy/pull/4/files#r990352747

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _verify_valid_seats(self):
Pending https://github.com/UlisesRivadeneyra/Open-Academy/pull/4/files#r990354189

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'title': "Incorrect 'seats' value",
Pending https://github.com/UlisesRivadeneyra/Open-Academy/pull/4/files#r990356655

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'message': "The number of available seats may not be negative",
Same

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'title': "Too many attendees",
Same

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                    'message': "Increase seats or remove excess attendees",
Same

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +        for record in self:
Pending

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                raise exceptions.ValidationError_("A session's instructor can't be an attendee")
???

2022-10-10 21:23 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +
Please organize the methods. See the guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models in `In a Model attribute order should be`

2022-10-10 22:07 UTC, UlisesRivadeneyra commented on open_academy/views/open_academy_session_views.xml
> +        <field name="name">openacademy.session_view_tree</field>
I have all names with _, are all names wrong?

2022-10-10 22:11 UTC, edy1192 commented on open_academy/views/open_academy_session_views.xml
> +        <field name="name">openacademy.session_view_tree</field>
Yes, please don't combine . and _. View's name is always with .

2022-10-10 22:14 UTC, edy1192 commented on open_academy/views/open_academy_session_views.xml
> +    <record model="ir.ui.view" id="session_view_tree">
First ID then model. See the guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#252security-view-and-action
```suggestion
        <record id="session_view_tree" model="ir.ui.view" >
```

Please apply this suggestion in all records.

2022-10-11 18:29 UTC, UlisesRivadeneyra commented
HI @edy1192 i added the modifications that you request.
Greetings, ulises

2022-10-11 21:35 UTC, edy1192 requested changes

2022-10-11 21:35 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _onchange_valid_seats(self):
Guidelines says: Onchange method: the onchange method pattern is `_onchange_<field_name>`

This should be:
```suggestion
    def _onchange_seats(self):
```

2022-10-12 02:52 UTC, UlisesRivadeneyra commented
Hi @edy1192 y change the last comment that you give me

2022-10-12 04:14 UTC, UlisesRivadeneyra commented
Hi @edy1192 i just resolve the last comment

2022-10-12 15:25 UTC, edy1192 requested changes

2022-10-12 15:25 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +    def _check_instructor_not_in_attendees(self):
Constraints methods go before onchanges. 

```
In a Model attribute order should be
Private attributes (_name, _description, _inherit, ...)
Fields declarations
SQL constraints
Default method and _default_get
Compute and search methods in the same order than field declaration
**Constrains methods (@api.constrains) and onchange methods (@api.onchange)**
CRUD methods (ORM overrides)
Action methods
And finally, other business methods.
```

2022-10-12 15:25 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                         compute='_get_hours', inverse='_set_hours')
Where is the compute method and inverse method? And I don't see where you use this field?

2022-10-12 15:25 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                record.taken_seats = 100.0 * len(record.attendee_ids) / record.seats
You had applied this change, why did you remove it?

2022-10-12 16:46 UTC, UlisesRivadeneyra commented
Hi @edy1192 i already ordered the session.py file like the guideines says and i add the hours in the gant view, i also add the parentesis in the taken seats.

2022-10-13 15:34 UTC, edy1192 approved these changes

2022-10-13 15:52 UTC, merged