[ADD]open_academy: Added reports,wizard and i18n T#60931
UlisesRivadeneyra/Open-Academy pull request #8
Opened 2022-10-14 15:45 UTC by UlisesRivadeneyra

Added the folder i18n with files inside that are diferent lenguages for the odoo modules -all.pot
-de.po
-nb_NO.po
-zh_HK.po

Added reports folder that contains an xml to generate a report file and view in odoo -openacademy_session_reports.xml

Added wizard folder that contain an odoo wizard pop up in sessions model -open_academy_wizard_views.xml
-open_academy_wizard.py

2022-10-14 18:19 UTC, UlisesRivadeneyra commented
Hi @edy1192 , mi pr is ready to be reviewed with all exercises of buiding a module

2022-10-14 19:34 UTC, edy1192 requested changes

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +"                                duracion:"
```suggestion
"                                duración:"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr ""
```suggestion
msgstr "Activo"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Añadir asistente"
```suggestion
msgstr "Añadir asistentes"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Nombre para mostrar"
Standard is:
```suggestion
msgstr "Nombre mostrado"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Agrupar por"
```suggestion
msgstr "Agrupado por"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "ID"
When both terms are the same, no translation is added.

```suggestion
msgstr ""
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Instructor"
When both terms are the same, no translation is added.

```suggestion
msgstr ""
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Última vez modificado por"
Standard is:
```suggestion
msgstr "Última modificación el"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Última vez actualizado por"
Standard is:
```suggestion
msgstr "Última actualización por"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Última actualización en"
```suggestion
msgstr "Última actualización el"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Pizarron de la sesión"
```suggestion
msgstr "Tablero de la sesión"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "NOmbre de la sesión"
```suggestion
msgstr "Nombre de la sesión"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/models/open_academy_partner.py
> +from odoo import models, fields
Rename this file check the file in main branch https://github.com/UlisesRivadeneyra/Open-Academy/blob/main/open_academy/models/res_partner.py

2022-10-14 19:34 UTC, edy1192 commented on open_academy/models/open_academy_partner.py
> +class Partner(models.Model):
Fix this https://github.com/UlisesRivadeneyra/Open-Academy/blob/main/open_academy/models/res_partner.py#L4

2022-10-14 19:34 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                raise exceptions.ValidationError_("A session's instructor can't be an attendee.")
I don't see the translation for this text.

2022-10-14 19:34 UTC, edy1192 commented on open_academy/views/open_academy_course_views.xml
> +                        <field name="session_ids"></field>
You duplicate this fields.

2022-10-14 19:34 UTC, edy1192 commented on open_academy/views/open_academy_menu_views.xml
> +    <menuitem id="menu_board_session" name="Session Dashboard" parent="base.menu_reporting_dashboard"
Why this parent? Use the open_academy_root_menu
```suggestion
    <menuitem id="menu_board_session" name="Session Dashboard" parent="base.menu_reporting_dashboard"
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/views/open_academy_partner_views.xml
> +<?xml version="1.0" encoding="utf-8"?>
Check this file in main branch https://github.com/UlisesRivadeneyra/Open-Academy/blob/main/open_academy/views/res_partner_views.xml

2022-10-14 19:34 UTC, edy1192 commented on open_academy/wizard/open_academy_wizard.py
> +        return self.env['openacademy.session'].browse(self._context.get('active_id'))
This method should be after fields see guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models
```suggestion
    def _default_session_id(self):
```

When you move it you need to change the field and use lambda function in the default parameter to find the method.
`default=lambda self: self._default_session_id()`

2022-10-14 19:34 UTC, edy1192 commented on open_academy/wizard/open_academy_wizard.py
> +        return {}
This is not necessary.

```suggestion
```

2022-10-14 19:34 UTC, edy1192 commented on open_academy/wizard/open_academy_wizard_views.xml
> +                    <field name="session_id" widget="many2many_list"/>
I think this widget is  not necessary.

```suggestion
                    <field name="session_id"/>
```

2022-10-14 19:35 UTC, edy1192 commented
Fix the PR's description please.

2022-10-15 21:30 UTC, UlisesRivadeneyra commented
hi @edy1192 i modify the code that you put me in the comment
Cheers, Ulises

2022-10-17 14:50 UTC, edy1192 requested changes

2022-10-17 14:50 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr "Última vez modificado el"
Pending https://github.com/UlisesRivadeneyra/Open-Academy/pull/8#discussion_r996069553

2022-10-17 14:50 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                raise exceptions.ValidationError_("A session's instructor can't be an attendee.")
Pending

2022-10-17 16:13 UTC, edy1192 requested changes

2022-10-17 16:13 UTC, edy1192 commented on open_academy/models/open_academy_session.py
> +                raise exceptions.ValidationError_("A session's instructor can't be an attendee.")
Add translations to onchange's message

2022-10-17 17:04 UTC, UlisesRivadeneyra commented
@edy1192 i already change the comments that you give me with the new translations.

2022-10-17 17:10 UTC, edy1192 approved these changes
Apply my comment in your next PR please.

2022-10-17 17:10 UTC, edy1192 commented on open_academy/i18n/es.po
> +msgstr ""
Missing translation.

2022-10-17 17:11 UTC, edy1192 approved these changes

2022-10-17 17:11 UTC, merged